# Site settings
title: Sim Hup Seng Services
email: simhupsengservices@gmail.com
description: Bringing you the best of our portable toilets in Singapore.
baseurl: "/company" # the subpath of your site, e.g. /blog
url: "https://mojojojo99.github.io" # the base hostname & protocol for your site
staticman_url: "https://jojo-static.herokuapp.com/v3/entry/github/mojojojo99/company/master/comments"

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown